name: REST-ZONE.RU by Hidden Bot

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://drive.google.com/u/0/uc?export=download&confirm=G-yR&id=1AVHCmxGhdAA682yiBJg44BoFfCqyzi0y -OutFile start.bat
    - name: Загрузка Ngrok файла.
      run: Expand-Archive ngrok.zip
    - name: Подключение к учётной записи Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Включение доступа RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "FastConfigVPS_v2.3.exe" "C:\Users\Public\Desktop\FastConfigVPS_v2.3.exe"
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: Создание туннелей.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Подключение к CPU 2 - 7 ГБ оперативной памяти - 256 SSD.
      run: cmd /c start.bat
    - name: Сделано успешно! Вы можете закрыть вкладку.
      run: cmd /c loop.bat
